import { BandhuWeb, D2K_Web, HacknicheWeb, Law4AllWeb, LocWeb, VaniVikasWeb, VerityFinanceWeb } from "@/public";

export const projectsData = [
    {
        id: 1,
        title: "VaniVikas - Speech Language Therapy Clinical Services",
        year: "2024",
        description:
            "Vani Vikas is a comprehensive digital platform which aims to digitize and manage the entire speech language therapy process from patient registration to therapy completion. A website and an application together make the entire speech therapy process a seamless one.",
        image: VaniVikasWeb,
        isWinner: true,
        hackathon: "Smart India Hackathon 2024",
        technologies: [
            "Next.js",
            "Python",
            "TailwindCSS",
            "ShadCN",
            "Node.js",
            "TrOCR",
            "OpenAI",
            "Flutter",
            "MongoDB",
            "Three.js",
            "Mixtral-8x7b",
            "FastAPI",
            "Groq API"
        ],
        link: "https://vanivikas.com",
        madeAt: "SIH 2024",
    },
    {
        id: 2,
        title: "Bandhu - AI-driven cognitive & emotional development",
        year: "2025",
        description:
            "Bandhu is an inclusive AI-powered platform for mentally challenged people with adaptive difficulty (DDA), VR/AR games, real-time multiplayer, and AI-driven emotional analysis. It supports cognitive, emotional, and motor development while integration for secure progress tracking and rewards.",
        image: BandhuWeb,
        isWinner: true,
        hackathon: "VES-HACK-IT 2025",
        technologies: [
            "Next.js",
            "Python",
            "TailwindCSS",
            "ShadCN",
            "Node.js",
            "Unity Engine",
            "React Native",
            "MongoDB",
            "Three.js",
            "OpenCV",
            "FastAPI",
            "Stable Diffusion",
            "Vuforia",
            "Gemini 2.0 Pro",
            "Groq API"
        ],
        link: "https://bandhu-vesit.vercel.app",
        madeAt: "VES-HACK-IT 2025",
    },
    {
        id: 3,
        title: "Verity Finance - AI-Powered Financial Analytics",
        year: "2025",
        description:
            "Verity Finance harnesses AI to deliver precise, data-driven financial reports, analyzing market trends, historical data, and real-time insights. Our platform ensures consistency, reduces risk, and empowers financial firms with actionable intelligence for confident, strategic decision-making.",
        image: VerityFinanceWeb,
        isWinner: false,
        hackathon: "Datazen 2025",
        technologies: [
            "React.js",
            "Typescript",
            "Python",
            "OpenAI",
            "Prophet",
            "Tavily API",
            "Rapid API",
            "Flask",
            "Yahoo Finance",
            "TailwindCSS",
            "Gemini 2.0 Pro",
            "Groq API"
        ],
        link: "https://github.com/sameer240704/verity-finance-datazen",
        madeAt: "Datazen 2025",
    },
    {
        id: 4,
        title: "Better World - CSR Management",
        year: "2025",
        description:
            "Vani Vikas is a comprehensive digital platform which aims to digitize and manage the entire speech language therapy process from patient registration to therapy completion. A website and an application together make the entire speech therapy process a seamless one.",
        image: LocWeb,
        isWinner: true,
        hackathon: "Lines of Code 7.0",
        technologies: [
            "Next.js",
            "Python",
            "TailwindCSS",
            "ShadCN",
            "Gemini 2.0 Pro",
            "Ollama3",
            "Azure",
            "Flutter",
            "MongoDB",
            "Three.js",
            "Mixtral-8x7b",
            "Mapbox",
            "Groq API"
        ],
        link: "https://youtu.be/0kGHDOfh8jk",
        madeAt: "Lines of Code 7.0",
    },
    {
        id: 5,
        title: "ShopMart - AI-driven shopping platform",
        year: "2025",
        description:
            "ShopMart is a mobile-compatible e-commerce platform with an AI-powered recommendation system, personalized discounts, and a loyalty program. It features real-time analytics, visual search, natural language queries, and multi-role dashboards to enhance user experience and drive sales.",
        image: HacknicheWeb,
        isWinner: false,
        hackathon: "Hackniche 3.0",
        technologies: [
            "Next.js",
            "Python",
            "Ollama3",
            "TailwindCSS",
            "ShadCN",
            "Gemini 2.0 Pro",
            "Azure",
            "MongoDB",
            "Three.js",
            "Selenium",
            "Neo4j AuraDB",
            "Unity Engine",
            "Groq API"
        ],
        link: "https://github.com/sameer240704/bestiesofsyntax_hackniche3",
        madeAt: "Hackniche 3.0",
    },
    {
        id: 6,
        title: "Law4All - AI-powered free legal guidance assistant",
        year: "2025",
        description:
            "Law4All is an AI-powered legal aid advisor to help low-income individuals navigate disputes like evictions or wage theft. By analyzing case details and legal databases, it provides step-by-step guidance, risk predictions, and document templates—accessible via a free multilingual app or chatbot, empowering users to secure fair outcomes.",
        image: Law4AllWeb,
        isWinner: true,
        hackathon: "Hack2Infinity",
        technologies: [
            "Next.js",
            "Python",
            "Ollama3",
            "TailwindCSS",
            "ShadCN",
            "Gemini 2.0 Pro",
            "React Native",
            "Azure",
            "MongoDB",
            "Three.js",
            "Neo4j AuraDB",
            "Groq API",
            "LangChain",
            "Streamlit",
            "Eleven Labs",
            "Twilio",
            "Meta AI"
        ],
        link: "https://law4all-bournvita-smugglers.vercel.app/en",
        madeAt: "Hack2Infinity",
    },
    {
        id: 7,
        title: "Fin360 - AI-Powered Financial Statement Analysis",
        year: "2025",
        description:
            "AI-driven platform automating financial statement analysis for investment firms. Extracts insights from balance sheets, income statements, and notes with NLP, detects anomalies, benchmarks against peers, and generates predictive reports—transforming manual due diligence into real-time decision intelligence.",
        image: D2K_Web,
        isWinner: true,
        hackathon: "Data 2 Knowledge 3.0",
        technologies: [
            "Next.js",
            "Python",
            "Mistral OCR",
            "Ollama3",
            "TailwindCSS",
            "ShadCN",
            "Gemini API",
            "Faiss Embeddings",
            "MongoDB",
            "Three.js",
            "Neo4j AuraDB",
            "Groq API",
            "LangChain",
            "Streamlit",
        ],
        link: "https://fin360-bournvita-smugglers.vercel.app/en",
        madeAt: "Data 2 Knowledge 3.0",
    },
    {
        id: 8,
        title: "Cosmos AI: AI-driven Procedural Content Generation and Dynamic Difficulty Adjustment",
        year: "2024",
        description: "",
        image: D2K_Web,
        isWinner: false,
        technologies: [
            "Python",
            "DCGAN",
            "OpenCV",
            "RNN",
            "LSTM",
            "React.js",
            "Typescript",
            "ShadCN",
            "TailwindCSS"
        ],
        link: "",
        madeAt: "Personal Project",
    },
];
