import {
    FaReact,
    FaNodeJs,
    FaHtml5,
    FaCss3,
    FaSass,
    FaAws,
    FaJava,
    FaFigma,
    FaDocker,
    FaBootstrap,
    FaDatabase,
    FaXbox,
    FaGitlab,
    FaGitAlt,
    FaRust,
    FaGithub,
    FaPython,
    FaLinux,
} from "react-icons/fa";
import { VscAzure, VscVscode } from "react-icons/vsc";
import {
    SiNextdotjs,
    SiNginx,
    SiTypescript,
    SiOpencv,
    SiLangchain,
    SiMongodb,
    SiEpicgames,
    SiPytorch,
    SiHuggingface,
    SiUnity,
    SiBlender,
    SiNpm,
    SiPostman,
    SiTailwindcss,
    SiUnrealengine,
    SiMysql,
    SiTensorflow,
    SiRockstargames,
    SiVite,
    SiCanva,
    SiRiotgames,
    SiNintendoswitch,
    SiGodotengine
} from "react-icons/si";
import { TbBrandKotlin } from "react-icons/tb";
import { RiJavascriptFill } from "react-icons/ri";
import {
    BiLogoPostgresql,
    BiLogoDiscordAlt,
    BiLogoDjango,
    BiLogoFirebase,
    BiLogoFlask,
    BiLogoRedux,
    BiLogoCPlusPlus,
} from "react-icons/bi";
import { FaGolang } from "react-icons/fa6";
import { IoLogoGameControllerB } from "react-icons/io";

export const techIcons = [
    FaReact,
    FaFigma,
    FaNodeJs,
    FaHtml5,
    FaCss3,
    RiJavascriptFill,
    SiRockstargames,
    SiTypescript,
    FaDocker,
    SiLangchain,
    SiEpicgames,
    FaGithub,
    FaJava,
    FaBootstrap,
    BiLogoFlask,
    BiLogoFirebase,
    SiCanva,
    FaAws,
    SiVite,
    FaLinux,
    SiPostman,
    VscAzure,
    SiNginx,
    SiNintendoswitch,
    FaPython,
    SiRiotgames,
    FaSass,
    SiNextdotjs,
    BiLogoDjango,
    BiLogoPostgresql,
    FaGitlab,
    FaXbox,
    SiUnrealengine,
    FaGitAlt,
    VscVscode,
    BiLogoDiscordAlt,
    SiUnity,
    SiHuggingface,
    IoLogoGameControllerB,
    SiNpm,
    SiMysql,
    SiBlender,
    SiGodotengine,
    BiLogoRedux,
    SiPytorch,
    TbBrandKotlin,
    FaDatabase,
    SiTailwindcss,
    SiTensorflow,
    FaGolang,
    SiMongodb,
    SiOpencv,
    FaRust,
    BiLogoCPlusPlus,
];