import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const starWarsJedi = localFont({
  src: [{ path: "../public/fonts/Starjedi.ttf" }],
  variable: "--font-jedi",
});

const starWarsJediOutline = localFont({
  src: [{ path: "../public/fonts/StarOutline.ttf" }],
  variable: "--font-outline",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${starWarsJedi.variable} ${starWarsJediOutline.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
